scala_version = "2.12.10"
scala_version_short = "2.12"
elastic_version = ""
cassandra_version = ""
kafka_version = ""
zookeeper_version = ""
play_version = ""

gremlin_version = "2.6.0"

java_deps = [
    "ch.qos.logback:logback-classic:1.2.3",
    "com.datastax.cassandra:cassandra-driver-core:3.7.1",
    "com.ecyrd.speed4j:speed4j:0.18",
    "com.fasterxml.jackson.core:jackson-core:2.10.0",
    "com.github.andrewoma.dexx:collection:0.7",
    "com.github.tomakehurst:wiremock:2.25.1",
    "com.google.code.findbugs:jsr305:3.0.2",
    "com.google.guava:guava:28.1-jre",
    "com.ning:async-http-client:1.9.40",
    "com.spatial4j:spatial4j:0.5",
    "com.tinkerpop.blueprints:blueprints-core:{}" % gremlin_version,
    "com.tinkerpop.gremlin:gremlin-groovy:{}" % gremlin_version,
    "com.thaiopensource:jing:20091111",
    "com.typesafe:config:1.4.0",
    "commons-io:commons-io:2.6",
    "commons-codec:commons-codec:1.13",
    "commons-lang:commons-lang:2.6",
    "com.jcraft:jsch:0.1.55",
    "jakarta.ws.rs:jakarta.ws.rs-api:2.1.6",
    "joda-time:joda-time:2.10.4",
    "junit:junit:4.12",
    "mx4j:mx4j-tools:3.0.1",
    "org.lz4:lz4-java:1.6.0",
    "net.lingala.zip4j:zip4j:2.2.3",
    "net.sf.ehcache:ehcache:2.10.2",
    "org.apache.cassandra:apache-cassandra:{}" % cassandra_version,
    "org.apache.commons:commons-compress:1.19",
    "org.apache.commons:commons-lang3:3.9",
    "org.apache.commons:commons-csv:1.7",
    "org.apache.httpcomponents:httpclient:4.5.10",
    "org.apache.httpcomponents:httpcore:4.4.12",
    # "org.apache.abdera" % art % "1.1.3",
    "org.apache.kafka:kafka-clients:{}" % kafka_version,
    "org.apache.logging.log4j:log4j-to-slf4j:2.12.1",
    "org.apache.tika:tika-core:1.22",
    "org.apache.thrift:libthrift:0.9.3",
    "org.apache.zookeeper:zookeeper:{}" % zookeeper_version,
    "org.aspectj:aspectjweaver:1.8.9",
    "org.codehaus.groovy:groovy-all:2.4.7",
    "org.codehaus.plexus:plexus-archiver:4.2.0",
    "org.codehaus.plexus:plexus-container-default:2.0.0" # "1.6",
    "org.codehaus.plexus:plexus-utils:3.3.0",
    "org.codehaus.woodstox:woodstox-asl:3.2.7",
    "org.elasticsearch:elasticsearch:{}" % elastic_version,
    "org.elasticsearch.client:transport:{}" % elastic_version,
    "org.elasticsearch.distribution.zip:elasticsearch-oss" % elastic_version,
    "org.elasticsearch:metrics-elasticsearch-reporter:2.2.0",
    "org.hdrhistogram:HdrHistogram:2.1.11",
    "org.jfarcand:wcs:1.3",
    "org.jdom:jdom2:2.0.6",
    "org.joda:joda-convert:2.2.1",
    "org.openrdf.sesame:sesame-runtime:4.1.2",
    "org.pac4j:play-pac4j_scala2.11:1.3.0",
    "org.pac4j:pac4j-saml:1.7.0",
    "org.pac4j:pac4j-oauth:1.7.0",
    "org.pac4j:pac4j-openid:1.7.0",
    "org.slf4j:slf4j-api:1.7.28",
    "org.yaml:snakeyaml:1.25",
    "xerces:xercesImpl:2.12.0",
    "xml-apis:xml-apis:1.4.01",
    "uk.org.lidalia:sysout-over-slf4j:1.0.2",
    "org.xerial.snappy:snappy-java:1.1.2.4",
    "io.netty:netty-all:4.1.42.Final",
    "io.dropwizard.metrics:metrics-core:4.1.1",
]

circe_version = "0.12.2"
metrics4_version = "4.1.1"
bytecompressor_version = "1.2.2"

scala_deps = [
    # "com.whisk" %% art % "0.9.7",
    "com.github.t3hnar:scala-bcrypt:4.1",
    "com.dimafeng:testcontainers-scala:0.33.0",
    "com.lihaoyi:ujson:0.8.0",
    "com.pauldijou:jwt-core:4.1.0",
    "com.lightbend.akka:akka-stream-alpakka-cassandra:1.1.2",
    "com.typesafe.scala-logging:scala-logging:3.9.2",
    "com.typesafe.akka:akka-stream-kafka:1.1.0",
    "com.typesafe.akka:akka-stream-contrib:0.10",
    "com.typesafe.akka:akka-http:10.1.10",
    "com.typesafe.akka:akka-actor:2.5.26",
    "com.typesafe.play:twirl-api:1.3.13",
    "com.typesafe.play:play-json:{}" % play_version,
    "com.typesafe.play:play:{}" % play_version,
    "com.twitter:chill-akka:0.5.2",
    "eu.piotrbuda:scalawebsocket:0.1.1",
    "io.circe:circe-core:{}" % circe_version,
    "io.circe:circe-generic:{}" % circe_version,
    "io.circe:circe-parser:{}" % circe_version,
    "net.jcazevedo:moultingyaml:0.4.1",
    "nl.grons:metrics4-scala:{}" % metrics4_version,
    "nl.grons:metrics4-akka_a25:{}" % metrics4_version,
    "nl.grons:metrics4-scala-hdr:{}" % metrics4_version,
    "org.rogach:scallop:3.3.1",
    "org.scalacheck:scalacheck:1.14.2",
    "org.scalatest:scalatest:3.0.8",
    "org.scala-lang.modules:scala-parser-combinators:1.0.4",
    "org.scala-lang.modules:scala-xml:1.2.0",
    "nl.gn0s1s:bump:0.1.3",
    "org.apache.kafka:kafka" % kafka_version,
    "org.scala-lang:scala-library:{}" % scala_version,
    "org.scala-lang.modules:scala-collection-compat:2.1.3"
]

jena_deps = [
    "apache-jena-libs",
    "apache-jena-osgi",
    "jena",
    "jena-arq",
    "jena-base",
    "jena-core",
    "jena-csv",
    "jena-cmds",
    "jena-elephas",
    "jena-elephas-common",
    "jena-elephas-commonjena-elephas-common",
    "jena-elephas-io",
    "jena-elephas-mapreduce",
    "jena-elephas-stats",
    "jena-extras",
    "jena-iri",
    "jena-jdbc",
    "jena-jdbc-core",
    "jena-jdbc-driver-bundle",
    "jena-jdbc-driver-mem",
    "jena-jdbc-driver-remote",
    "jena-jdbc-driver-tdb",
    "jena-maven-tools",
    "jena-osgi",
    "jena-permissions",
    "jena-querybuilder",
    "jena-sdb",
    "jena-shaded-guava",
    "jena-spatial",
    "jena-tdb",
    "jena-text",
]
